baseURL = "https://likipiki.gitlab.io"
title = "Likipiki"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© 2021 Формошлеп Арт Студия"

theme = "PaperMod"

# Missing translations will default to this content language
defaultContentLanguage = "ru"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
defaultTheme = "auto"
yandexMetrika = "71539801"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
comments = false
hidemeta = false
showtoc = false
tocopen = true

[params.fuseOpts]
	isCaseSensitive = false
	shouldSort = true
	location = 0.0
	distance = 1000.0
	threshold = 0.4
	minMatchCharLength = 0.0
	keys = [
		"title",
		"permalink",
		"summary",
		"content"
	]

[minify]
disableXML = true
minifyOutput = true

[outputs]
home = [
  "HTML",
  "RSS", 
  "JSON"
]

[menu]
    [[menu.main]]
    name = "Посты"
    weight = -30
    identifier = "posts"
    url = "/archives/"
	[[menu.main]]
	name = "Тэги"
	identifier = "tags"
	url = "/tags/"
    weight = -20
	[[menu.main]]
	name = "Поиск"
	identifier = "search"
	url = "/search/"
    weight = -10

[languages]
# edit this block for your own language
    [languages.ru]
    lang = "ru"
    languageName = "Russian"
    weight = 1
