baseURL = "https://likipiki.gitlab.io"
title = "Likipiki"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© 2021 формошлеп арт студия"

theme = "PaperMod"

# Missing translations will default to this content language
defaultContentLanguage = "ru"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[params]
env = "production"
defaultTheme = "auto"
yandexMetrika = "71539801"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = true
disableSpecial1stPost = false
comments = false
hidemeta = false
showtoc = false
tocopen = true

[minify]
disableXML = true
minifyOutput = true

[menu]
    [[menu.main]]
    name = "Посты"
    weight = -30
    identifier = "posts"
    url = "/archives/"
	[[menu.main]]
	name = "Категории"
	identifier = "categories"
	url = "/categories/"
    weight = -20
	[[menu.main]]
	name = "Тэги"
	identifier = "tags"
	url = "/tags/"
    weight = -10

[languages]
# edit this block for your own language
    [languages.ru]
    lang = "ru"
    languageName = "Russian"
    weight = 1
